name: Continuous Deployment

on: 
    release:
        types: [published]

jobs:
    deploy:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2

        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name:  Deploy to server
          run: ssh -o StrictHostKeyChecking=no root@10.1.0.3 '/home/trmc/domains/club.trmc.nl/public_html/update_server_files.sh'